// Author: dWallet Labs, Ltd.
// SPDX-License-Identifier: CC-BY-NC-ND-4.0

//! This file implements the Signature Partial Decryption round party for Class Groups

use super::*;
use crate::class_groups::{ecdsa::Presign, DKGDecentralizedPartyOutput};
use crate::ecdsa::sign::centralized_party::message::class_groups::Message;
use crate::ecdsa::VerifyingKey;
use crate::languages::class_groups::verify_committed_linear_evaluation;
use ::class_groups::equivalence_class::EquivalenceClassOps;
use ::class_groups::MultiFoldNupowAccelerator;
use ::class_groups::{encryption_key, CompactIbqf, EquivalenceClass};
use ::class_groups::{
    equivalence_class, CiphertextSpacePublicParameters, RandomnessSpaceGroupElement,
    RandomnessSpacePublicParameters,
};
use ::class_groups::{CiphertextSpaceGroupElement, EncryptionKey};
use crypto_bigint::Int;
use group::GroupElement;

impl Party {
    /// This function implements step (2d) of the Sign protocol:
    /// Verifies zk-proofs of C_{k}, C_{\alpha}, C_{\beta}, C_{kx}, R, R_{B} ,\textsf{ct}_{\alpha,\beta}. and \textsf{ct}_A.
    /// src: <https://eprint.iacr.org/archive/2025/297/20250522:123428>
    /// Verify the validity of the encrypted signature parts sent by the centralized party.
    /// If this function returns `Ok()`, it means that a valid signature over `message` is
    /// guaranteed to be able to be generated by the decentralized party, whenever a threshold of
    /// honest parties decides to engage in the signing protocol.
    ///
    /// Note: `hashed_message` is a `Scalar` which must be a hash on the message bytes translated into a
    /// 32-byte number.
    pub fn verify_encryption_of_signature_parts_prehash_class_groups<
        const SCALAR_LIMBS: usize,
        const FUNDAMENTAL_DISCRIMINANT_LIMBS: usize,
        const NON_FUNDAMENTAL_DISCRIMINANT_LIMBS: usize,
        const MESSAGE_LIMBS: usize,
        GroupElement: VerifyingKey<SCALAR_LIMBS> + Copy,
    >(
        protocol_public_parameters: &crate::class_groups::ProtocolPublicParameters<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            GroupElement,
        >,
        dkg_output: DKGDecentralizedPartyOutput<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            GroupElement,
        >,
        presign: Presign<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            GroupElement,
        >,
        sign_message: Message<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            MESSAGE_LIMBS,
            GroupElement,
        >,
        hashed_message: GroupElement::Scalar,
    ) -> crate::Result<()>
    where
        Int<SCALAR_LIMBS>: Encoding,
        Uint<SCALAR_LIMBS>: Encoding,
        Uint<SCALAR_LIMBS>: Encoding + ConcatMixed<StatisticalSecuritySizedNumber> + for<'a> From<&'a <Uint<SCALAR_LIMBS> as ConcatMixed<StatisticalSecuritySizedNumber>>::MixedOutput> + for<'a> From<&'a <Uint<SCALAR_LIMBS> as ConcatMixed<StatisticalSecuritySizedNumber>>::MixedOutput>,
        Int<FUNDAMENTAL_DISCRIMINANT_LIMBS>: Encoding,
        Uint<FUNDAMENTAL_DISCRIMINANT_LIMBS>: Encoding,
        Int<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>: Encoding,
        Uint<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>: Encoding,
        EquivalenceClass<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>: group::GroupElement<
            Value = CompactIbqf<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>,
            PublicParameters = equivalence_class::PublicParameters<
                NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            >,
        > + EquivalenceClassOps<
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            MultiFoldNupowAccelerator = MultiFoldNupowAccelerator<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>,
        >,
        EncryptionKey<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            GroupElement,
        >: AdditivelyHomomorphicEncryptionKey<
            SCALAR_LIMBS,
            PublicParameters = encryption_key::PublicParameters<
                SCALAR_LIMBS,
                FUNDAMENTAL_DISCRIMINANT_LIMBS,
                NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
                group::PublicParameters<GroupElement::Scalar>,
            >,
            PlaintextSpaceGroupElement = GroupElement::Scalar,
            RandomnessSpaceGroupElement = RandomnessSpaceGroupElement<
                FUNDAMENTAL_DISCRIMINANT_LIMBS,
            >,
            CiphertextSpaceGroupElement = CiphertextSpaceGroupElement<
                NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            >,
        >,
        encryption_key::PublicParameters<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            group::PublicParameters<GroupElement::Scalar>,
        >: AsRef<
            homomorphic_encryption::GroupsPublicParameters<
                group::PublicParameters<GroupElement::Scalar>,
                RandomnessSpacePublicParameters<FUNDAMENTAL_DISCRIMINANT_LIMBS>,
                CiphertextSpacePublicParameters<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>,
            >,
        >,
        Uint<MESSAGE_LIMBS>: Encoding,
    {
        let (
            encryption_of_masked_decentralized_party_nonce_share_before_displacing,
            first_coefficient_commitment,
            second_coefficient_commitment
        ): (CiphertextSpaceGroupElement<NON_FUNDAMENTAL_DISCRIMINANT_LIMBS>, GroupElement, GroupElement) = Self::verify_encryption_of_signature_parts_prehash::<SCALAR_LIMBS, SCALAR_LIMBS, GroupElement, EncryptionKey<SCALAR_LIMBS, FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS, GroupElement>>(
            hashed_message, presign.session_id,
            sign_message.public_signature_nonce,
            sign_message.decentralized_party_nonce_public_share,
            sign_message.signature_nonce_share_commitment,
            sign_message.alpha_displacer_commitment.clone(),
            sign_message.beta_displacer_commitment.clone(),
            sign_message.signature_nonce_share_by_secret_share_commitment,
            sign_message.non_zero_commitment_to_signature_nonce_share_proof,
            sign_message.non_zero_commitment_to_alpha_displacer_share_proof,
            sign_message.commitment_to_beta_displacer_share_uc_proof,
            sign_message.proof_of_equality_between_nonce_share_and_nonce_share_by_secret_key_share_commitments,
            sign_message.public_signature_nonce_proof,
            sign_message.decentralized_party_nonce_public_share_displacement_proof,
            &protocol_public_parameters.scalar_group_public_parameters,
            &protocol_public_parameters.group_public_parameters,
            &protocol_public_parameters.encryption_scheme_public_parameters,
            dkg_output.clone(),
            presign.clone(),
        )?;

        let commitment_scheme_public_parameters =
            pedersen::PublicParameters::derive::<SCALAR_LIMBS, GroupElement>(
                protocol_public_parameters
                    .scalar_group_public_parameters
                    .clone(),
                protocol_public_parameters.group_public_parameters.clone(),
            )?;

        // $C_\alpha$
        let alpha_displacer_commitment = GroupElement::new(
            sign_message.alpha_displacer_commitment,
            &protocol_public_parameters.group_public_parameters,
        )?;

        // $C_\beta$
        let beta_displacer_commitment = GroupElement::new(
            sign_message.beta_displacer_commitment,
            &protocol_public_parameters.group_public_parameters,
        )?;

        let (
            ..,
            encryption_of_displaced_decentralized_party_nonce_share_protocol_context,
            encryption_of_partial_signature_protocol_context,
        ) = generate_protocol_contexts(presign.session_id, &dkg_output.public_key);

        // (d). Verify $\pi_{\textsf{ct}_{\alpha,\beta}}$.
        verify_committed_linear_evaluation::<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            MESSAGE_LIMBS,
            GroupElement,
        >(
            presign.encryption_of_mask,
            encryption_of_masked_decentralized_party_nonce_share_before_displacing.value(),
            sign_message.encryption_of_displaced_decentralized_party_nonce_share,
            beta_displacer_commitment,  // $C_\beta$
            alpha_displacer_commitment, // $C_\alpha$
            sign_message.encryption_of_displaced_decentralized_party_nonce_share_proof,
            commitment_scheme_public_parameters.clone().into(),
            protocol_public_parameters
                .scalar_group_public_parameters
                .clone(),
            protocol_public_parameters.group_public_parameters.clone(),
            protocol_public_parameters
                .encryption_scheme_public_parameters
                .clone(),
            &encryption_of_displaced_decentralized_party_nonce_share_protocol_context,
            true,
        )?;

        // (d). Verify $\pi_{\textsf{ct}_{A}}$.
        verify_committed_linear_evaluation::<
            SCALAR_LIMBS,
            FUNDAMENTAL_DISCRIMINANT_LIMBS,
            NON_FUNDAMENTAL_DISCRIMINANT_LIMBS,
            MESSAGE_LIMBS,
            GroupElement,
        >(
            presign.encryption_of_mask,
            presign.encryption_of_masked_decentralized_party_key_share,
            sign_message.encryption_of_partial_signature,
            first_coefficient_commitment,  // $C_1$
            second_coefficient_commitment, // $C_2$
            sign_message.encryption_of_partial_signature_proof,
            commitment_scheme_public_parameters.clone().into(),
            protocol_public_parameters
                .scalar_group_public_parameters
                .clone(),
            protocol_public_parameters.group_public_parameters.clone(),
            protocol_public_parameters
                .encryption_scheme_public_parameters
                .clone(),
            &encryption_of_partial_signature_protocol_context,
            true,
        )?;

        Ok(())
    }
}
