// Author: dWallet Labs, Ltd.
// SPDX-License-Identifier: CC-BY-NC-ND-4.0

//! This module wraps around the `bulletproofs` crate, and implements the `RangeProof` and
//! `AggregatableRangeProof` traits.
//!
//! We extend `bulletproofs` to support aggregation of an arbitrary number of parties (not
//! necessarily a power of two),
//!
//! We do that by padding the provers list with artificial provers that have a witness of zeros.
//! They also use zero nonces. In this way, everyone can simulate them efficiently and pad the
//! proof.

use std::{array, iter};

use bulletproofs::{BulletproofGens, PedersenGens};
use crypto_bigint::{U256, U64};
use curve25519_dalek::ristretto::RistrettoPoint;
use merlin::Transcript;
use serde::{Deserialize, Serialize};

use commitment::{MultiPedersen, Pedersen};
use group::{helpers::FlatMapResults, ristretto, CsRng, GroupElement as _, Transcribeable};

use crate::range::CommitmentSchemeCommitmentSpaceGroupElement;
use crate::{range::CommitmentScheme, Error, ErrorKind, Result};

/// A wrapper around `bulletproofs::RangeProof` that optionally adds the `aggregation_commitments`
/// for aggregated range proofs.
///
/// Whilst bulletproofs claim to have a constant-size proof and support
/// aggregation, these claims are false: the commitments aren't aggregated but are instead
/// concatenated, so that the commitment for the aggregated proofs is O(n) in the number of parties
/// and so is the verification time.
///
/// This breaks our `range::RangeProof` and `proofs::aggregation` interfaces, but since this is due
/// to the fact bulletproofs aren't actually aggregatable, we decided to think of the aggregated
/// proof as a (non-constant) struct that holds both what bulletproofs says is the proof and the
/// commitment.
///
/// This allows `RangeProof::verify()` to get the actual aggregated commitment as the parameter
/// and compare them to the non-aggregated `aggregation_commitments`, whilst still allowing for the
/// implementation to use the individual `commitment` of each player to verify the proof.
///
/// For non-aggregated commitment, the `commitment` generated by `bulletproofs` are valid and
/// `aggregation_commitments` can remain empty.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RangeProof {
    pub proof: bulletproofs::RangeProof,
    pub aggregation_commitments: Vec<ristretto::GroupElement>,
}

pub const RANGE_CLAIM_BITS: usize = 32;

pub const COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS: usize = ristretto::SCALAR_LIMBS;

impl super::RangeProof<COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS> for RangeProof {
    const NAME: &'static str = "Bulletproofs over the Ristretto group";

    const RANGE_CLAIM_BITS: u32 = RANGE_CLAIM_BITS as u32;

    type RangeClaimGroupElement = ristretto::Scalar;

    type CommitmentScheme<const NUM_RANGE_CLAIMS: usize> = MultiPedersen<
        NUM_RANGE_CLAIMS,
        COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
        ristretto::Scalar,
        ristretto::GroupElement,
    >;

    type PublicParameters<const NUM_RANGE_CLAIMS: usize> = PublicParameters<NUM_RANGE_CLAIMS>;

    fn prove<const NUM_RANGE_CLAIMS: usize>(
        _public_parameters: &Self::PublicParameters<NUM_RANGE_CLAIMS>,
        witnesses: Vec<
            commitment::MessageSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                Self::CommitmentScheme<NUM_RANGE_CLAIMS>,
            >,
        >,
        commitments_randomness: Vec<
            commitment::RandomnessSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                Self::CommitmentScheme<NUM_RANGE_CLAIMS>,
            >,
        >,
        transcript: Transcript,
        rng: &mut impl CsRng,
    ) -> Result<(
        Self,
        Vec<
            commitment::CommitmentSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                Self::CommitmentScheme<NUM_RANGE_CLAIMS>,
            >,
        >,
    )> {
        let number_of_witnesses = witnesses.len();

        // As bulletproofs proves a single witness, flatten the witnesses vector
        // from an entry over `NUM_RANGE_CLAIMS` to a vector of individual range claims.
        let witnesses: Vec<_> = witnesses
            .into_iter()
            .flat_map(<[_; NUM_RANGE_CLAIMS]>::from)
            .collect();

        // Bulletproofs think of range claims as numbers and not scalars.
        // Transitioning, whilst ensuring they are in range.
        let witnesses: Vec<_> = witnesses.into_iter().map(U256::from).collect();

        if witnesses
            .iter()
            .any(|witness| witness >= &(U256::ONE << RANGE_CLAIM_BITS))
        {
            return Err(Error::from(ErrorKind::InvalidParameters))?;
        }

        let witnesses: Vec<u64> = witnesses
            .into_iter()
            .map(|witness| U64::from(&witness).into())
            .collect();

        // Similarly, flatten commitments randomnesses.
        let commitments_randomness: Vec<_> = commitments_randomness
            .into_iter()
            .flat_map(|multicommitment_randomness| {
                <[_; NUM_RANGE_CLAIMS]>::from(multicommitment_randomness)
            })
            .map(curve25519_dalek::scalar::Scalar::from)
            .collect();

        // Bulletproofs' API supports power-of-two-sized batching exclusively.
        // To handle that, we pad to the next power-of-two with a witness zero and randomness zero.
        let padded_witnesses_length = witnesses
            .len()
            .checked_next_power_of_two()
            .ok_or_else(|| Error::from(ErrorKind::InvalidParameters))?;
        let mut iter = witnesses.into_iter();
        let witnesses: Vec<u64> = iter::repeat_with(|| iter.next().unwrap_or(0u64))
            .take(padded_witnesses_length)
            .collect();

        let mut iter = commitments_randomness.into_iter();
        let commitments_randomness: Vec<curve25519_dalek::scalar::Scalar> =
            iter::repeat_with(|| {
                iter.next()
                    .unwrap_or(curve25519_dalek::scalar::Scalar::ZERO)
            })
            .take(padded_witnesses_length)
            .collect();

        let bulletproofs_generators = BulletproofGens::new(RANGE_CLAIM_BITS, witnesses.len());
        let commitment_generators = PedersenGens::default();

        let (proof, commitments) = bulletproofs::RangeProof::prove_multiple_with_rng(
            bulletproofs_generators,
            commitment_generators,
            transcript,
            witnesses.as_slice(),
            commitments_randomness.as_slice(),
            RANGE_CLAIM_BITS,
            rng,
        )
        .map_err(|_| Error::from(ErrorKind::InvalidParameters))?;

        let mut commitments_iter = commitments
            .into_iter()
            .map(|compressed_commitment| {
                compressed_commitment
                    .try_into()
                    .map_err(|_| Error::from(ErrorKind::InternalError))
            })
            .collect::<Result<Vec<_>>>()?
            .into_iter();

        let commitments: Result<Vec<_>> = iter::repeat_with(|| {
            // Un-flatten individual commitments to a multi-commitment,
            // to fit the `RangeProof` API which returns a vector of commitments over
            // `NUM_RANGE_CLAIMS` elements.
            array::from_fn(|_| {
                commitments_iter
                    .next()
                    .ok_or_else(|| Error::from(ErrorKind::InvalidParameters))
            })
            .flat_map_results()
            .map(
                commitment::CommitmentSpaceGroupElement::<
                    COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                    Self::CommitmentScheme<NUM_RANGE_CLAIMS>,
                >::from,
            )
        })
        .take(number_of_witnesses)
        .collect();

        Ok((RangeProof::new(proof), commitments?))
    }

    fn verify<const NUM_RANGE_CLAIMS: usize>(
        &self,
        _public_parameters: &Self::PublicParameters<NUM_RANGE_CLAIMS>,
        commitments: Vec<
            commitment::CommitmentSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                Self::CommitmentScheme<NUM_RANGE_CLAIMS>,
            >,
        >,
        transcript: Transcript,
        rng: &mut impl CsRng,
    ) -> Result<()> {
        let commitments = if self.aggregation_commitments.is_empty() {
            let commitments: Vec<_> = commitments
                .into_iter()
                .flat_map(|multicommitment| {
                    <[ristretto::GroupElement; NUM_RANGE_CLAIMS]>::from(multicommitment)
                })
                .collect();

            let padded_commitments_length = commitments
                .len()
                .checked_next_power_of_two()
                .ok_or_else(|| Error::from(ErrorKind::InvalidParameters))?;
            let identity = commitments
                .first()
                .ok_or_else(|| Error::from(ErrorKind::InvalidParameters))?
                .neutral();
            let mut iter = commitments.into_iter();

            iter::repeat_with(|| iter.next().unwrap_or(identity))
                .take(padded_commitments_length)
                .collect()
        } else {
            if commitments
                != Self::aggregate_commitments(
                    commitments.len(),
                    self.aggregation_commitments.clone(),
                )?
            {
                return Err(Error::from(ErrorKind::ProofVerification));
            }

            self.aggregation_commitments.clone()
        };

        let compressed_commitments: Vec<_> = commitments
            .into_iter()
            .map(RistrettoPoint::from)
            .map(|point| point.compress())
            .collect();

        let bulletproofs_generators =
            BulletproofGens::new(RANGE_CLAIM_BITS, compressed_commitments.len());
        let commitment_generators = PedersenGens::default();

        let mut transcript = transcript;

        self.proof
            .verify_multiple_with_rng(
                &bulletproofs_generators,
                &commitment_generators,
                &mut transcript,
                compressed_commitments.as_slice(),
                RANGE_CLAIM_BITS,
                rng,
            )
            .map_err(|e| match e {
                bulletproofs::ProofError::VerificationError => Error::from(ErrorKind::OutOfRange),
                _ => Error::from(ErrorKind::InvalidParameters),
            })
    }
}

#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub struct PublicParameters<const NUM_RANGE_CLAIMS: usize> {
    pub commitment_scheme_public_parameters: commitment::PublicParameters<
        COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
        MultiPedersen<
            NUM_RANGE_CLAIMS,
            COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
            ristretto::Scalar,
            ristretto::GroupElement,
        >,
    >,
    pub number_of_range_claims: usize,
}

impl<const NUM_RANGE_CLAIMS: usize> Transcribeable for PublicParameters<NUM_RANGE_CLAIMS> {
    type CanonicalRepresentation = Self;
}

impl<const NUM_RANGE_CLAIMS: usize> Default for PublicParameters<NUM_RANGE_CLAIMS> {
    fn default() -> Self {
        let scalar_public_parameters = ristretto::scalar::PublicParameters::default();
        let group_public_parameters = ristretto::group_element::PublicParameters::default();

        let commitment_generators = PedersenGens::default();

        let commitment_scheme_public_parameters = commitment::PublicParameters::<
            COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
            Pedersen<
                1,
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                ristretto::Scalar,
                ristretto::GroupElement,
            >,
        >::new::<
            COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
            ristretto::Scalar,
            ristretto::GroupElement,
        >(
            scalar_public_parameters,
            group_public_parameters,
            [commitment_generators.B.compress().try_into().unwrap()],
            commitment_generators
                .B_blinding
                .compress()
                .try_into()
                .unwrap(),
        )
        .into();

        Self {
            commitment_scheme_public_parameters,
            number_of_range_claims: NUM_RANGE_CLAIMS,
        }
    }
}

impl<const NUM_RANGE_CLAIMS: usize>
    AsRef<
        commitment::PublicParameters<
            COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
            MultiPedersen<
                NUM_RANGE_CLAIMS,
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                ristretto::Scalar,
                ristretto::GroupElement,
            >,
        >,
    > for PublicParameters<NUM_RANGE_CLAIMS>
{
    fn as_ref(
        &self,
    ) -> &commitment::PublicParameters<
        COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
        MultiPedersen<
            NUM_RANGE_CLAIMS,
            COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
            ristretto::Scalar,
            ristretto::GroupElement,
        >,
    > {
        &self.commitment_scheme_public_parameters
    }
}

impl RangeProof {
    pub fn new(proof: bulletproofs::RangeProof) -> Self {
        Self {
            proof,
            aggregation_commitments: vec![],
        }
    }

    pub fn new_aggregated<const NUM_RANGE_CLAIMS: usize>(
        proof: bulletproofs::RangeProof,
        number_of_witnesses: usize,
        aggregation_commitments: Vec<ristretto::GroupElement>,
    ) -> Result<(
        Self,
        Vec<
            commitment::CommitmentSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                CommitmentScheme<
                    COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                    NUM_RANGE_CLAIMS,
                    Self,
                >,
            >,
        >,
    )> {
        let aggregated_commitments =
            Self::aggregate_commitments(number_of_witnesses, aggregation_commitments.clone())?;

        let range_proof = Self {
            proof,
            aggregation_commitments,
        };

        Ok((range_proof, aggregated_commitments))
    }

    pub fn aggregate_commitments<const NUM_RANGE_CLAIMS: usize>(
        number_of_witnesses: usize,
        aggregation_commitments: Vec<ristretto::GroupElement>,
    ) -> Result<
        Vec<
            commitment::CommitmentSpaceGroupElement<
                COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                CommitmentScheme<
                    COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS,
                    NUM_RANGE_CLAIMS,
                    Self,
                >,
            >,
        >,
    > {
        let number_of_padded_witnesses = number_of_witnesses
            .checked_mul(NUM_RANGE_CLAIMS)
            .and_then(usize::checked_next_power_of_two)
            .ok_or_else(|| Error::from(ErrorKind::InvalidParameters))?;

        if aggregation_commitments.is_empty()
            || number_of_padded_witnesses == 0
            || !aggregation_commitments.len().is_power_of_two()
            || aggregation_commitments.len() <= number_of_padded_witnesses
        {
            return Err(Error::from(ErrorKind::InvalidParameters));
        }

        // safe to divide as both are non-zero powers of two, and aggregation_commitments.len()
        // bigger than number_of_padded_witnesses.
        let number_of_padded_parties = aggregation_commitments.len() / number_of_padded_witnesses;

        let bulletproofs_aggregated_commitments = (0..number_of_padded_witnesses)
            .map(|i| {
                (0..number_of_padded_parties)
                    .map(|j: usize| {
                        let res = j
                            .checked_mul(number_of_padded_witnesses)
                            .and_then(|index| index.checked_add(i))
                            .and_then(|index| aggregation_commitments.get(index).cloned());

                        res.ok_or_else(|| Error::from(ErrorKind::InternalError))
                    })
                    .collect::<Result<Vec<_>>>()
            })
            .collect::<Result<Vec<_>>>()?;

        let bulletproofs_aggregated_commitments: Result<Vec<_>> =
            bulletproofs_aggregated_commitments
                .into_iter()
                .map(|v| {
                    v.into_iter()
                        .reduce(|a, b| a + b)
                        .ok_or_else(|| Error::from(ErrorKind::InternalError))
                })
                .collect();

        let mut bulletproofs_aggregated_commitments_iter =
            bulletproofs_aggregated_commitments?.into_iter();

        iter::repeat_with(|| {
            array::from_fn(|_| {
                bulletproofs_aggregated_commitments_iter
                    .next()
                    .ok_or_else(|| Error::from(ErrorKind::InternalError))
            })
            .flat_map_results()
            .map(
                CommitmentSchemeCommitmentSpaceGroupElement::<
                    { COMMITMENT_SCHEME_MESSAGE_SPACE_SCALAR_LIMBS },
                    NUM_RANGE_CLAIMS,
                    Self,
                >::from,
            )
        })
        .take(number_of_witnesses)
        .collect::<Result<Vec<_>>>()
    }
}

// Since exporting rust `#[cfg(test)]` is impossible, these test helpers exist in a dedicated
// feature-gated module.
#[cfg(feature = "test_helpers")]
pub mod test_helpers {
    use crate::range::bulletproofs::RangeProof;

    pub fn new_range_proof(proof: bulletproofs::RangeProof) -> RangeProof {
        RangeProof::new(proof)
    }
}
