name: Vale Lint Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: errata-ai/vale-action@reviewdog
